ZheskiProject/ZheskiProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from users.views import reg
from users.views import authorization
# from users.views import loginMain
from users.views import prototype
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg/', reg, name='reg'),
    path('auth/', authorization, name='authorization'),
    # path('loginMain/', loginMain, name='usersMain'),
    path('users/', include('users.urls', namespace='users')),
    path('prototype/', prototype, name='prototype'),
    path('', index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ZheskiProject/users/urls.py
from django.urls import path

from users.views import loginMain, profile

app_name = 'users'

urlpatterns = [
    path('loginMain/', loginMain, name='loginMain'),
    path('profile/', profile, name='profile')
] 

ZheskiProject/main/models.py
from django.db import models

# Create your models here.

ZheskiProject/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    # UserName = models.CharField('UserName', max_length=32)
    # Password = models.CharField('Password', max_length=32)
    # Email = models.EmailField('Email')

ZheskiProject/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from users.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'FormAuthorization_Data_UserName_Input', 'placeholder':'Имя Пользователя',
        'id': 'FormAuthorization_Data-Form_Input'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'FormAuthorization_Data_Password_Input', 'placeholder':'Пароль',
        'id': 'FormAuthorization_Data-Form_Input'
    }))

    class Meta:
        model = User
        fields = ('UserName', 'Password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'FormRegistration_Data_UserName_Input', 'placeholder':'Имя Пользователя',
        'id': 'FormRegistration_Data-Form_Input'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'FormRegistration_Data_Mail_Input', 'placeholder':'E-mail',
        'id': 'FormRegistration_Data-Form_Input'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'FormRegistration_Data_Password_Input', 'placeholder':'Пароль',
        'id': 'FormRegistration_Data-Form_Input'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'FormRegistration_Data_Password-Replay_Input', 'placeholder':'Подтвердите пароль',
        'id': 'FormRegistration_Data-Form_Input'
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': False}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'readonly': True}))
    image = forms.ImageField(widget=forms.FileInput(attrs={}), required=False)
    class Meta:
        model = User
        fields = ('username', 'image', 'email')

ZheskiProject/main/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'main/index.html')

ZheskiProject/users/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth
from .models import User
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm

# Create your views here.
def reg(request):
    return render(request, 'users/reg.html')
def authorization(request):
    return render(request, 'users/authorization.html')
def loginMain(request):
    if request.method == 'POST':
        formReg = UserRegistrationForm(data=request.POST)
        form = UserLoginForm(data=request.POST)
        if formReg.is_valid():
            formReg.save()
            return HttpResponseRedirect(reverse('users:profile'))
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserLoginForm()
        formReg = UserRegistrationForm()

    context = {'formReg': formReg, 'form': form}
    
    if request.method == 'POST' and not form.is_valid():
        context['error_message'] = "Неправильные учетные данные. Пожалуйста, попробуйте снова."
    return render(request, 'users/loginMain.html', context)
def prototype(request):
    return render(request, 'users/prototype.html')
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {'form': form}
    return render(request, 'users/profile.html', context)

ZheskiProject/main/templates/main/class.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body>
    <div class="mainSection">
        <div class="nav">
            <a class="nav_title" href="#" >Twitter</a>
            <ul class="navColumn">
                <li class="navColumn-item"><a href="">News</a></li>
                <li class="navColumn-item"><a href="">Explorer</a></li>
                <li class="navColumn-item"><a href="">Notifications</a></li>
                <li class="navColumn-item"><a href="">Messages</a></li>
                <li class="navColumn-item"><a href="">Settings</a></li>
                <li class="navColumn-item"><a href="">Profile</a></li>
                <li class="navColumn-item"><a href="">More</a></li>
                <li class="navColumn-item"><button class="createPostButton">+</li>
            </ul>
            <div class="navProfile">
                <img class="navProfile-img" src="" alt="#">
                <div class="navProfile-nameColumn">
                    <div class="navProfile-nameColumn_upper">Dmitriy</div>
                    <div class="navProfile-nameColumn_lower">#Dmitriy</div>
                </div>
                <button class="navProfile-button">&#8230;</button>

            </div>
            <div class="rightBlock"></div>
        </div>
        {% block body %}
        {% endblock %}
        
    </div>
</body>
</html>

ZheskiProject/main/templates/main/index.html
{% extends 'main/class.html' %}
{% block body %}

{% endblock %}

ZheskiProject/users/templates/users/authorization.html
{% extends 'users/class.html' %}
{% block title %} Авторизация {% endblock %}
{% block titleForm %}
<h1 class="FormRegistration_title">Авторизация</h1>
{% endblock %}
{% block FormRegistration_Data %}
<div class="FormRegistration_Data_Information">
    <div class="FormAuthorization_Data_UserName" id="FormRegistration_Data-Form">Имя Пользователя:</div> 
    <p class="FormAuthorization_Data_Password">Пароль:</p>
    </div>
    <div class="FormRegistration_Data_Input">
    <input type="text" class="FormAuthorization_Data_UserName_Input" id="FormAuthorization_Data-Form_Input">
    <input type="text" class="FormAuthorization_Data_Password_Input" id="FormAuthorization_Data-Form_Input">
    </div>
    <div class="FormRegistration_Data_Account_True"><a href="{% url 'reg' %}">Нет аккаунта?</a></div>
{% endblock %}

ZheskiProject/users/templates/users/class.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
</head>

<body>
    <div class="FormRegistration">
        <div class="FormRegistration_block">
        <div class="FormRegistration_title-Form">
            {% block titleForm %}
            {% endblock %}
        </div>
            <div class="FormRegistration_Data">
                {% block FormRegistration_Data %}
                {% endblock %}
                <input type="submit" class="FormRegistration_Data_Button">
            </div>
        </div>
    </div>
</body>
</html>

ZheskiProject/users/templates/users/loginMain.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" href="{% static 'users/css/prototype.css' %}">
<script src="{% static 'users/js/prototype.js'%}"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <div class="panelLogo">
    <img class="logo" src="{% static 'users/img/apple.png' %}" alt="logo">
  </div>
    <div class="panelForActions">
      <div class="panelForActionsMain">
        <div class="panelForActionsName"><h1>ZhekiProject</h1></div>
        <div class="panelForActionsDescription"><h2>Присоединяйтесь сегодня.</h2></div>
        <button class="panelButton" id="loginButton" onclick="toggleModal('loginModal')">Войти</button>
        <div class="panelForActionsSeparation"><h2>или</h2></div>
        <button class="panelButton" id="registerButton" onclick="toggleModal('registerModal')">Зарегистрироваться</button>
      </div>
        <div id="loginModal" class="modal">
          <div class="modal-content">
            <span class="close" onclick="toggleModal('loginModal')">&times;</span>
            <h2 class="namePanel">Авторизация</h2>
            <form action="{% url 'users:loginMain'%}" method="post">
              {% csrf_token %}
                <div class="FormRegistration_Data_Information">
                </div>
                    <div class="FormRegistration_Data_Input">
                      {% if error_message %}
                      <div class="error-message">{{ error_message }}</div>
                      {% endif %}
                    {{ form.username}}
                    {{ form.password }}
                    </div>
                    <div class="FormAuthorization_Float">
                    <input type="submit" class="FormAuthorization_Data_Button">
                    <div class="FormAuthorization_Data_Account_True"><a href="#" onclick="toggleModal('loginModal'); toggleModal('registerModal')">Нет аккаунта?</a></div>
                  </div>
            </form>
          </div>
        </div>
        
        {% if popup %}
        <div id="registerModal" class="modal">
            <div class="modal-content">
                <span class="close" onclick="toggleModal('registerModal')">&times;</span>
                <h2 class="namePanel">Регистрация</h2>
                <form action="{% url 'users:loginMain' %}" method="post">
                    {% csrf_token %}
                    <div class="FormRegistration_Data_Input">
                        {{ formReg.username }}
                        {{ formReg.email }}
                        {{ formReg.password1 }}
                        {{ formReg.password2 }}
                    </div>
                    <input type="submit" value="Зарегистрироваться">
                </form>
            </div>
        </div>
        {% endif %}
        
        <div id="registerModal" class="modal">
          <div class="modal-content">
            <span class="close" onclick="toggleModal('registerModal')">&times;</span>
            <h2 class="namePanel">Регистрация</h2>
            <form action="{% url 'users:loginMain'%}" method="post">
              {% csrf_token %}
                    <div class="FormRegistration_Data_Input">
                    {{ formReg.username }}
                    {{ formReg.email }}
                    {{ formReg.password1 }}
                    {{ formReg.password2 }}
                    </div>
                    <div class="FormRegistration_Float">
                    <input type="submit" class="FormRegistration_Data_Button">
                    <div class="FormRegistration_Data_Account_True"><a href="#" onclick="toggleModal('registerModal'); toggleModal('loginModal')">Есть аккаунт?</a></div>
                  </div>
            </form>
          </div>
        </div>
</div>
<div class="Float">
  <a href="#" class="FloatText">О нас</a>
  <a href="#" class="FloatText">Справочный центр</a>
  <a href="#" class="FloatText">Политика конфиденциальности</a>
  <a href="#" class="FloatText">Настройки</a>
</div>
</body>
</html>

ZheskiProject/users/templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Hif
    <form action="{% url 'users:profile' %}" method="post">
        {% csrf_token %}
        {{ form.img }}
        {{ form.username }}
        {{ form.email }}
        <input type="submit" value="Сделать">
    </form>
</body>
</html>

ZheskiProject/users/templates/users/prototype.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" href="{% static 'users/css/prototype.css' %}">
<script src="{% static 'users/js/prototype.js'%}"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="panelForActions">
        <div><h1>Название</h1></div>
        <div><h2>Описание</h2></div>
        <button class="panelButton" id="loginButton" onclick="toggleModal('loginModal')">Войти</button>
        <button class="panelButton" id="registerButton" onclick="toggleModal('registerModal')">Зарегистрироваться</button>
        
        <div id="loginModal" class="modal">
          <div class="modal-content">
            <span class="close" onclick="toggleModal('loginModal')">&times;</span>
            <h2 class="namePanel">Авторизация</h2>
            <form action="#" method="post">
                <div class="FormRegistration_Data_Information">
                    <div class="FormAuthorization_Data_UserName" id="FormRegistration_Data-Form">Имя Пользователя:</div> 
                    <p class="FormAuthorization_Data_Password">Пароль:</p>
                    </div>
                    <div class="FormRegistration_Data_Input">
                    <input type="text" class="FormAuthorization_Data_UserName_Input" id="FormAuthorization_Data-Form_Input">
                    <input type="text" class="FormAuthorization_Data_Password_Input" id="FormAuthorization_Data-Form_Input">
                    </div>
                    <input type="submit" class="FormAuthorization_Data_Button">
                    <div class="FormAuthorization_Data_Account_True"><a href="#" onclick="toggleModal('loginModal'); toggleModal('registerModal')">Нет аккаунта?</a></div>
            </form>
          </div>
        </div>
        
        <div id="registerModal" class="modal">
          <div class="modal-content">
            <span class="close" onclick="toggleModal('registerModal')">&times;</span>
            <h2 class="namePanel">Регистрация</h2>
            <form action="#" method="post">
                <div class="FormRegistration_Data_Information">
                    <div class="FormRegistration_Data_UserName" id="FormRegistration_Data-Form">Имя Пользователя:</div> 
                    <div class="FormRegistration_Data_Mail" id="FormRegistration_Data-Form">Эл. Почта:</div>
                    <p class="FormRegistration_Data_Password" id="FormRegistration_Data-Form">Пароль:</p>
                    <p class="FormRegistration_Data_Password-Replay" id="FormRegistration_Data-Form">Повтор пароля:</p>
                    </div>
                    <div class="FormRegistration_Data_Input">
                    <input type="text" class="FormRegistration_Data_UserName_Input" >
                    <input type="text" class="FormRegistration_Data_Mail_Input" id="FormRegistration_Data-Form_Input">
                    <input type="text" class="FormRegistration_Data_Password_Input" id="FormRegistration_Data-Form_Input">
                    <input type="text" class="FormRegistration_Data_Password-Replay_Input" id="FormRegistration_Data-Form_Input">
                    </div>
                    <input type="submit" class="FormRegistration_Data_Button">
                    <div class="FormRegistration_Data_Account_True"><a href="#" onclick="toggleModal('registerModal'); toggleModal('loginModal')">Есть аккаунт?</a></div>
            </form>
          </div>
        </div>
        
</div>
</body>
</html>

ZheskiProject/users/templates/users/reg.html
{% extends 'users/class.html' %}
{% block title %} Регистрация {% endblock %}
{% block titleForm %}
<h1 class="FormRegistration_title">Регистрация</h1>
{% endblock %}
{% block FormRegistration_Data %}
<div class="FormRegistration_Data_Information">
<div class="FormRegistration_Data_UserName" id="FormRegistration_Data-Form">Имя Пользователя:</div> 
<div class="FormRegistration_Data_Mail" id="FormRegistration_Data-Form">Эл. Почта:</div>
<p class="FormRegistration_Data_Password" id="FormRegistration_Data-Form">Пароль:</p>
<p class="FormRegistration_Data_Password-Replay" id="FormRegistration_Data-Form">Повтор пароля:</p>
</div>
<div class="FormRegistration_Data_Input">
<input type="text" class="FormRegistration_Data_UserName_Input" id="">
<input type="text" class="FormRegistration_Data_Mail_Input" id="FormRegistration_Data-Form_Input">
<input type="text" class="FormRegistration_Data_Password_Input" id="FormRegistration_Data-Form_Input">
<input type="text" class="FormRegistration_Data_Password-Replay_Input" id="FormRegistration_Data-Form_Input">
</div>
<div class="FormRegistration_Data_Account_True"><a href="{% url 'authorization' %}">Есть аккаунт?</a></div>
{% endblock %}